= Drupal 8 Multilingual Views
:published_at: 2017-05-21
:hp-tags: Drupal, Drupal8, Views, Multilingual, Multilingual Views

Views are part of the core in Drupal 8 but as expected there will always be some bugs. I will explain workaround for this https://www.drupal.org/node/2451657[issue] until they finally make fix part of Drupal 8. For short answer you can check my question and answer https://drupal.stackexchange.com/questions/236541/multilingual-views-hide-if-no-translation[here] and thanks to a user that pointed to issue I found a solution.

== The Problem
I had to implement blog as part of Drupal website, this was easy with views. I created a view that listed all articles (Content Type) and added **Content: Translation language** filter that I set to **Interface text language selected for page** also I had some additional filter that wasn’t translatable and that was making a problem. My view was showing only posts that were created on currently selected language. Since I had some posts on German that had a translation to English, they still were not showing in English and vice versa. By default, views are making a condition on **langcode** for every join, but my field wasn’t translatable so there was a problem if you condition by language. So what now? We need that filter, it decides on something major but it is same for all translation. Should I make it translatable and force the editor to choose same option for every translation? That would work, but why make the editor do that and also allow a possibility of additional mistakes.


== The Workaround
Remove the conditional from view and use https://api.drupal.org/api/drupal/core%21modules%21views%21views.api.php/function/hook_views_query_alter/8.2.x[hook_views_query_alter] to add your relationship and conditional.

[[app-listing]]
[source,php]
.MODULE.views_execution.inc
----
<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

function hook_views_query_alter(ViewExecutable $view, QueryPluginBase $query)
{
    if ($view->id() == 'your_view_id') {
        $definition = [
            'table' => 'node__field_content_type',
            'field' => 'entity_id',
            'left_table' => 'node_field_data',
            'left_field' => 'nid',
        ];
        $join = Drupal::service('plugin.manager.views.join')->createInstance('standard', $definition);
        $query->addRelationship('node__field_content_type', $join, 'node__field_content_type');
        
        // now add your untranslated field condition here:
        $query->addWhere('1', 'node__field_content_type.field_content_type_value', 1, '=');
    }
}
----
NOTE: This hook has to be in MODULE.views_execution.inc file, also *node__field_content_type.field_content_type_value* was the name of my field that I needed for conditional so be sure to change it to yours.

That would be it, I hope they fix this soon.